# C:\app\streamlit_financial_dashboard\.streamlit\secrets.toml

NEO4J_URI = "neo4j+s://f9f444b7.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "BhpVJhR0i8NxbDPU29OtvveNE8Wx3X2axPI7mS7zXW0"

OPENAI_API_KEY  = "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"
LLM_PROVIDER='openai'